config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  get 'rails/g'
  get 'rails/controller'
  get 'rails/Carts'
  get 'rails/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
  get '/product_view/:id', to: 'products#show'
  put '/product_edit/:id', to: 'products#edit'
  resources :products
  resources :registrations
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  post 'line_items' => "line_items#create"
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :carts
  resources :line_items
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
  belongs_to :user

  def sub_total
    sum =0
    self.line_items.each do |line_items|
      sum+= line_items.total_price
    end
    sum
  end

  def sum_quantity
    self.line_items.sum(:quantity)
  end
end

app/models/concerns/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  def total_price
    self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  validates :name, presence:true
  validates :price, presence:true
  validates :description, presence:true
  has_many :cart_items
  has_many :carts, through: :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  normalizes :email, with: ->(email){ email.strip.downcase }
  has_secure_password
  has_one :cart
  before_validation :check_uniqueness_errors
  enum role: {normal:0, admin:1}

  private
  def check_uniqueness_errors
    if self.errors[:name].any?
      self.errors.add(:name, "has already been taken")
    end
    if self.errors[:email].any?
      self.errors.add(:email, "has already been taken")
    end
  end

  def admin
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :current_cart
  private

  def login(user)
    session[:user_id] = user.id
    Current.user = user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def user_signed_in?
    !!current_user
  end

  helper_method :user_signed_in?

  def authenticate_user!
    redirect_to new_session_path, alert: 'Please log in' unless user_signed_in?
  end

  def require_admin
    unless current_user&.admin?
      redirect_to root_path, alert: "You are not authorized to access this page."
    end
  end
  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(:id => session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id] == nil
      user_id = session[:user_id]
      @current_cart = Cart.create(user_id:user_id)
      session[:cart_id] = @current_cart.id
    end
    @current_cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    cart = @current_cart
    cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController< ApplicationController
  def index
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  def create
    chosen_product = Product.find(params[:product])
    current_cart = @current_cart

    Rails.logger.info("Session[:cart_id]: #{session[:cart_id]}")

    if current_cart.products.include?(chosen_product)
      @line_item = current_cart.line_items.find_by(product: chosen_product)
      @line_item.quantity += 1
    else
      @line_item = LineItem.new
      @line_item.cart = current_cart
      @line_item.quantity = 1
      @line_item.product = chosen_product
    end
    @line_item.save
    redirect_to cart_path(current_cart)
  end

  def add_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity +=1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity -= 1
    if @line_item.quantity >0
      @line_item.save
    end
    redirect_to cart_path(@current_cart)
  end



  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to cart_path(@current_cart)
  end

  private
  def line_item_params
    params.require(:line_item).permit(:quantity, :product, :cart_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :require_admin, only:[:create, :update,:destroy, :edit, :new]

  def index
    @product = Product.all
    @cart = current_user&.cart || Cart.new
    render "/index"
  end

  def show
    @product = Product.find(params[:id])
    @cart = current_user&.cart || Cart.new
    render 'product_view_data'
  end

  def new
    @product = Product.new
    render 'product_create_form'
  end

  def create
    @product = Product.new(product_params)

    if @product.save
        redirect_to "/products", notice: "Product was successfully created."
    else
      redirect_to '/products/register'
    end
  end

  def edit
    @product = Product.find(params[:id])
    render 'product_edit_form'
  end

  def update
    if @product.update(product_params)
      redirect_to '/products', notice: "Product was successfully updated."
    else
      render 'product_edit_form'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: "Product was successfully destroyed."
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :description, :image)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)
    if @user.save
      login @user
      redirect_to root_path, notice: "Welcome to home"
    else
      flash.now[:alert] = "User creation failed"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def registration_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate_by(email: params[:email], password: params[:password])
    if user
      login user
      Rails.logger.info("User Login Successfully.")
      redirect_to root_path, notice: "You have signed successfully."
    else
      flash[:alert] = "Invalid email or password."
      render :new, status: :unprocessable_entity
    end
  end
  def destroy
    logout_user
    redirect_to root_path, alert: "You have been logged out."
  end

  private

  def logout_user
    reset_session
    Current.user = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">

      <h2>Cart</h2>
      <div class="card">
        <div class="card-body">
          <ul class="list-group">
            <% @cart.line_items.each do |line_item| %>
              <li class="list-group-item">
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <strong><%= line_item.product.name %></strong>
                    <span class="badge bg-primary rounded-pill ms-2">Quantity: <%= line_item.quantity %></span>
                  </div>
                  <div>
                    <span class="badge bg-secondary"><%= number_to_currency(line_item.product.price) %></span>
                    <span class="badge bg-secondary"><%= number_to_currency(line_item.total_price) %></span>
                    <div class="btn-group ms-2">
                      <%= button_to "Add one", line_item_add_path(:id => line_item), class: "btn btn-sm btn-outline-success", method: :post %>
                      <%= button_to "Reduce one", line_item_reduce_path(:id => line_item), class: "btn btn-sm btn-outline-warning", method: :post %>
                      <%= button_to "Remove item", line_item_path(line_item), class: "btn btn-sm btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                    </div>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
          <div class="mt-3">
            <h3>Subtotal: <%= number_to_currency(@cart.sub_total) %></h3>
            <div class="col">
              <div class="d-flex justify-content-between">
                <%= button_to "Empty cart", cart_path(@current_cart), class: "btn btn-danger", method: :delete %>
                <%= button_to "Check out", cart_path(@current_cart), class: "btn btn-success"%>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">E-Rails</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex align-items-center">
        <% if user_signed_in? %>
          <div class="cart-icon me-2">
            <i class="fa fa-shopping-cart"></i>
          </div>
          <div class="cart-info me-3">
            <span class="badge bg-primary"><%= @cart.sum_quantity %></span>
          </div>
          <%= button_to "Log out", new_session_path, method: :delete, class: "btn btn-danger me-2" %>
        <% else %>
          <%= link_to "Register", new_registration_path, class: "btn btn-success me-2" %>
          <%= link_to "Log in", new_session_path, class: "btn btn-primary" %>
        <% end %>
      </div>


    </div>
  </div>
</nav>

<%= yield %>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
</script>
</html>

app/views/products/product_create_form.html.erb
<%= form_for @product, html: { class: "needs-validation", novalidate: true } do |f| %>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="mb-3">
          <h2>Add Product</h2>
        </div>

        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control", :required => 'required' %>
          <div class="invalid-feedback">
            Please provide a name.
          </div>
        </div>

        <div class="mb-3">
          <%= f.label :description, class: "form-label" %>
          <%= f.text_area :description, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a description.
          </div>
        </div>

        <div class="mb-3">
          <%= f.label :price, class: "form-label" %>
          <%= f.number_field :price, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a valid price.
          </div>
        </div>

        <div class="mb-3">
          <%= f.label :image, class: "form-label" %>
          <%= f.file_field :image, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a valid price.
          </div>
        </div>

        <%= f.submit "Create Product", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/products/product_edit_form.html.erb
<%= form_for @product, html: { class: "needs-validation", novalidate: true } do |f| %>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="mb-3">
          <h2> Edit Product</h2>
        </div>

        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a name.
          </div>
        </div>

        <div class="mb-3">
          <%= f.label :description, class: "form-label" %>
          <%= f.text_area :description, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a description.
          </div>
        </div>

        <div class="mb-3">
          <%= f.label :price, class: "form-label" %>
          <%= f.number_field :price, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a valid price.
          </div>
        </div>
        
        <div class="mb-3">
          <%= f.label :image, class: "form-label" %>
          <%= f.file_field :image, class: "form-control", required: true %>
          <div class="invalid-feedback">
            Please provide a valid price.
          </div>
        </div>

        <%= f.submit "Edit Product", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/products/product_view_data.html.erb
<div class="container">
  <h2 class="text-center mt-4">Product</h2>
  <div class="row products">
    <div class="col-md-8 mx-auto">
      <div class="card shadow mb-4">
        <% if @product.image.attached? %>
          <%= image_tag url_for(@product.image), class: "card-img-top", style: "max-width: 900px; max-height: 500px;" %>
        <% else %>
          <p>No image available</p>
        <% end %>
        <div class="card-body">
          <h3 class="card-title mb-3"><%= @product.name %></h3>
          <p class="card-text mb-4"><%= @product.description %></p>
          <p class="card-text h4">$<%= @product.price %></p>
          <div class="row justify-content-center mt-4">
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <div class="col-auto">
                  <%= link_to "Edit", edit_product_url(id: @product.id), class: "btn btn-primary mr-2" %>
                </div>
                <div class="col-auto">
                  <%= button_to "Delete", @product, method: :delete, class: "btn btn-danger" %>
                </div>
              <% end %>
            <% end %>
            <% if user_signed_in? %>
              <div class="col-auto">
                <%= button_to "Add to Cart",line_items_path(:product => @product.id) %>
              </div>
            <% else %>
              <div class="col-auto">
                <%= link_to "AddToCart",new_session_path, class: "btn btn-success" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>